### ISSUE TITLE
Dealing with missing CRDs

### ISSUE THREAD

**Issue by y0ug** [dezeroku/home_server#60]
Hi,
I'm not sure how to contact you. Your repo was really inspiring but I've few questions. Especially how are dealing with missing CRD when you deploy additional resources using `bjw-s` `app-template` and the `rawResources`.

How are you planning to deal with the last version of cert-manager v1.16 where they inforce *Helm schema validation*?

Any place where I can chat up with you?

**Comment by y0ug** [comment]
I manage to deal with the problem with something like that and using `helmfile sync` instead of `apply`

```yaml
- name: metallb
  chart: metallb/metallb
  namespace: metallb-system
  values:
    - ./values/metallb.yaml.gotmpl

- name: metallb-post
  chart: bjw-s/app-template
  values:
    - ./values/metallb-post.yaml.gotmpl
  needs:
    - metallb-system/metallb

 - name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  #version: v1.15.3
  needs:
    - external-secrets/external-secrets
  values:
    - values/cert-manager.yaml.gotmpl

- name: cert-manager-post
  namespace: cert-manager
  chart: bjw-s/app-template
  needs:
    - cert-manager/cert-manager
  values:
    - values/cert-manager-post.yaml.gotmpl
```

I'm still wondering how your code is working without that and using apply? Because even with that I still have some issue like `no endpoints available for service "external-secrets-webhook"` where I guest I should have to set the flag wait:true
